name: garage
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  intl: ^0.20.2
  uuid: ^4.5.2
  go_router: ^17.0.1
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  equatable: ^2.0.7
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/logos/ford.png
    - assets/logos/honda.png
    - assets/logos/peugeot.png
    - assets/logos/suzuki.png
    - assets/logos/toyota.png
    - assets/logos/yamaha.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#1A1A2E"
    theme_color: "#2196F3"
